[tool.poetry]
name = "dot"
version = "3.0.0"
description = "My dotfiles"
authors = ["Tucker Beck <tucker.beck@gmail.com>"]
license = "MIT"
packages = [ { include = "dot_tools" } ]

[tool.poetry.dependencies]
python = "^3.8"
GitPython = "^3.1.8"
pendulum = "^2.1.2"
bidict = "^0.21.2"
click = "^7.1.2"
git-url-parse = "^1.2.2"
inflection = "^0.5.1"
loguru = "^0.5.3"
pprintpp = "^0.4.0"
py-buzz = "^2.0.0"
pydon = "^0.1.0"
pytest = "^6.1.1"
requests = "^2.24.0"
sh = "^1.14.0"
jira = "^2.0.0"
keyring = "^21.4.0"
addict = "^2.3.0"
toml = "^0.10.1"
pylint = "^2.6.0"
"keyrings.alt" = "^4.0.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
duck = 'dot_tools.bin.duck:main'
configure-dot = 'dot_tools.bin.configure_dot:main'
checkout-branch-by-pattern = 'dot_tools.bin.checkout_branch_by_pattern:main'
current-branch = 'dot_tools.bin.current_branch:main'
find-source-file = 'dot_tools.bin.find_source_file:main'
find-test-file = 'dot_tools.bin.find_test_file:main'
gittop = 'dot_tools.bin.gittop:main'
make-branch = 'dot_tools.bin.make_branch:main'
now = 'dot_tools.bin.now:main'
sep-bar = 'dot_tools.bin.sep_bar:main'
tag-version = 'dot_tools.bin.tag_version:main'
transpose = 'dot_tools.bin.transpose:main'
underlined-header = 'dot_tools.bin.underlined_header:main'
save-jira-password = 'dot_tools.bin.save_jira_password:main'
find-pyproject-toml = 'dot_tools.bin.find_pyproject_toml:main'
get-black-line-length = 'dot_tools.bin.get_black_line_length:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
