require("config.globals")
require("config.options")

require("setup.lazy")
require("setup.mason")
require("setup.mason-lsp")
require("setup.lualine")
require("setup.telescope")
require("setup.blink")
require("setup.lsp")
require("setup.neotest")
require("setup.treesj")
require("setup.tokyonight")
require("setup.ibl")
require("setup.treesitter")
require("setup.miniai")
require("setup.minialign")
require("setup.fterm")
require("setup.colorizer")
require("setup.dapui")
require("setup.copilot")
require("setup.smear")
require("setup.chunk")
require("setup.dropbar")
require("setup.illuminate")

require("user.clipboard")
require("user.linelen")
require("user.keymap")
require("user.reload")

require("config.commands")
